// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_qt_sample();
Q_GHS_KEEP_REFERENCE(qml_register_types_qt_sample)

class qt_samplePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    qt_samplePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_qt_sample;
        Q_UNUSED(registration)
    }
};



#include "qt-sampleplugin_qt_samplePlugin.moc"
