// default package
// Generated 2017-10-23 20:11:10 by Hibernate Tools 3.5.0.Final
package com.Unionfinance2.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BalanceId generated by hbm2java
 */
@Embeddable
public class BalanceId implements java.io.Serializable {

	private String inUnion;
	private Double income;

	private double balance;

	public BalanceId() {
	}

	public BalanceId(

	double balance) {
        this.balance = balance;
    }

	public BalanceId(String inUnion, Double income,

	double balance) {
       this.inUnion = inUnion;
       this.income = income;
       this.balance = balance;
    }

	@Column(name = "in_union", length = 30)
	public String getInUnion() {
		return this.inUnion;
	}

	public void setInUnion(String inUnion) {
		this.inUnion = inUnion;
	}

	@Column(name = "income", precision = 18, scale = 1)
	public Double getIncome() {
		return this.income;
	}

	public void setIncome(Double income) {
		this.income = income;
	}

	@Column(name = "balance", precision = 18, scale = 1)
	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BalanceId) ) return false;
		 BalanceId castOther = ( BalanceId ) other; 
         
		 return ( (this.getInUnion()==castOther.getInUnion()) || ( this.getInUnion()!=null && castOther.getInUnion()!=null && this.getInUnion().equals(castOther.getInUnion()) ) )
 && ( (this.getIncome()==castOther.getIncome()) || ( this.getIncome()!=null && castOther.getIncome()!=null && this.getIncome().equals(castOther.getIncome()) ) )
 && ( (this.getBalance()==castOther.getBalance()) || ( this.getBalance()!=null && castOther.getBalance()!=null && this.getBalance().equals(castOther.getBalance()) ) );
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInUnion() == null ? 0 : this.getInUnion().hashCode() );
         result = 37 * result + ( getIncome() == null ? 0 : this.getIncome().hashCode() );
         result = 37 * result + ( getBalance() == null ? 0 : this.getBalance().hashCode() );
         return result;
   }

}
