// default package
// Generated 2017-10-23 20:11:10 by Hibernate Tools 3.5.0.Final
package com.Unionfinance2.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Balance generated by hbm2java
 */
@Entity
@Table(name = "balance", catalog = "labour_db")
public class Balance implements java.io.Serializable {

	private BalanceId id;

	public Balance() {
	}

	public Balance(BalanceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "inUnion", column = @Column(name = "in_union", length = 30)),
			@AttributeOverride(name = "income", column = @Column(name = "income", precision = 18, scale = 1)),
			@AttributeOverride(name = "ifnull(zc.cost,0)", column = @Column(name = "IFNULL(zc.cost,0)", nullable = false, precision = 18, scale = 1)),
			@AttributeOverride(name = "balance", column = @Column(name = "balance", precision = 18, scale = 1)) })
	public BalanceId getId() {
		return this.id;
	}

	public void setId(BalanceId id) {
		this.id = id;
	}

}
