######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 2 10:28:48 2012
######################################################################

TEMPLATE = app
TARGET = 
QT += gui core webkit xml widgets webkitwidgets
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h rssxmlparser.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp rssxmlparser.cpp
