// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types__test_004();
Q_GHS_KEEP_REFERENCE(qml_register_types__test_004)

class _test_004Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    _test_004Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types__test_004;
        Q_UNUSED(registration)
    }
};



#include "_test_004plugin__test_004Plugin.moc"
