package com.example.documentforge.model;

import java.time.Instant;
import java.util.List;

/**
 * Result of a document generation request.
 */
public record GenerationResult(
		String id,
		DocumentType documentType,
		String prompt,
		String responseText,
		List<GeneratedFile> files,
		Instant createdAt,
		Status status,
		String errorMessage
) {

	/**
	 * Status of the generation request.
	 */
	public enum Status {
		PENDING,
		COMPLETED,
		FAILED
	}

	/**
	 * A file generated by Claude Skills.
	 */
	public record GeneratedFile(
			String fileId,
			String filename,
			long size,
			String mimeType
	) {
	}

	/**
	 * Check if generation was successful.
	 */
	public boolean success() {
		return status == Status.COMPLETED;
	}

	/**
	 * Check if generation is still pending.
	 */
	public boolean pending() {
		return status == Status.PENDING;
	}

	public static GenerationResult success(String id, DocumentType type, String prompt,
			String responseText, List<GeneratedFile> files) {
		return new GenerationResult(id, type, prompt, responseText, files, Instant.now(), Status.COMPLETED, null);
	}

	public static GenerationResult failure(String id, DocumentType type, String prompt, String errorMessage) {
		return new GenerationResult(id, type, prompt, null, List.of(), Instant.now(), Status.FAILED, errorMessage);
	}

	public static GenerationResult pending(String id, DocumentType type, String prompt) {
		return new GenerationResult(id, type, prompt, "Generating in background...", List.of(), Instant.now(), Status.PENDING, null);
	}

}
