///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.zeroturnaround:zt-exec:1.12
//DEPS com.fasterxml.jackson.core:jackson-databind:2.17.1
//JAVA 17
//FILES ExampleInfo.json
//SOURCES ../../../../integration-testing/jbang-lib/IntegrationTestUtils.java

/*
 * Integration test launcher for brave-chatbot
 * Uses centralized utilities from IntegrationTestUtils
 * Generated by scaffold_integration_test.py on 2025-08-02 14:26:17
 */

public class RunBraveChatbot {
    
    public static void main(String... args) throws Exception {
        IntegrationTestUtils.runIntegrationTest("brave-chatbot");
    }
}