// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types__test_001();
Q_GHS_KEEP_REFERENCE(qml_register_types__test_001)

class _test_001Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    _test_001Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types__test_001;
        Q_UNUSED(registration)
    }
};



#include "_test_001plugin__test_001Plugin.moc"
