# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, macos-latest ]
      fail-fast: false
      max-parallel: 64
    name: Test on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: brew install coreutils gnu-sed
        # https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        # https://docs.github.com/en/actions/learn-github-actions/expressions
        if: runner.os == 'macOS'
      - run: test/chore/integration-test.sh
      # https://remarkablemark.org/blog/2017/10/12/check-git-dirty/
      - name: Check git dirty
        run: |
          git status --short
          [ -z "$(git status --short)" ]
